# Generated by Django 5.2 on 2025-04-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('tag', models.CharField(choices=[('politics', 'Политика'), ('tech', 'Технологии'), ('business', 'Бизнес')], default='tech', max_length=20, verbose_name='Тег')),
                ('localisation', models.CharField(verbose_name='Локализация (язык)')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
    ]
