# Generated by Django 5.2 on 2025-04-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('sector', models.CharField(choices=[('IT', 'Информационные технологии'), ('FINANCE', 'Финансы'), ('EDUCATION', 'Образование'), ('OTHER', 'Другое')], default='IT', max_length=20, verbose_name='Сфера')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='Дата основания')),
                ('localisation', models.CharField(verbose_name='Локализация (язык)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
    ]
