# Generated by Django 5.2 on 2025-04-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(choices=[('ИТ', 'Информационные технологии'), ('Финансы', 'Финансы'), ('образование', 'Образование'), ('Другое', 'Другое')], max_length=20, null=True, verbose_name='Сфера'),
        ),
    ]
